### ISSUE TITLE
Import Module Exception

### ISSUE THREAD

**Issue by ghost** [Signiant/PaperWatch#6]
I have setup, built, deployed and added a manual subscription as per the instructions in the readme.

The LambdaLogConsumer Lambda that is created displays an error at the top of the page:

`An error occurred while listing cloudwatch-logs relations: 2 validation errors detected: Value '' at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+; Value '' at 'logGroupName' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 31c7b30f-eb8b-4db2-8d03-d27849332f0e)`

The log group name that I subscribed manually does fit those constraints.

And when logs are generated the LambdaLogConsumer  produces an error:

`{ 
   "errorType":"Runtime.ImportModuleError",
   "errorMessage":"Error: Cannot find module 'lambda'",
   "stack":[ 
      "Runtime.ImportModuleError: Error: Cannot find module 'lambda'",
      "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
      "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
      "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
      "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
      "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
      "    at Module.load (internal/modules/cjs/loader.js:653:32)",
      "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
      "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
      "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
      "    at startup (internal/bootstrap/node.js:283:19)"
   ]
}`

I'm unsure whether to two errors are related.

Any help on these issues would be appreciated

**Comment by timothysantos** [comment]
Hi @ccsam278 have you found a way to solve this? I'm encountering the same error message

**Comment by ghost** [comment]
Hi @timothysantos. I haven't found a solution to this problem. If you find one please update me, I'll do the same.

**Comment by esampaio** [comment]
@ccsam278 I assume you haven't found a solution yet, right?

**Comment by ghost** [comment]
@esampaio No. I have stopped trying at this point

**Comment by iwarshak** [comment]
I ran into this issue also. I created as derivative of this project that fits my needs: https://github.com/iwarshak/cloudwatch-to-papertrail-lambda

**Comment by esampaio** [comment]
@ccsam278 thanks for the quick response.
@iwarshak that looks great, thank you for sharing!
